version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: dockerfiles/rails/Dockerfile

    command: bash -c "ps aux && bundle exec unicorn -E production"
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
