version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: dockerfiles/rails/Dockerfile
    command: bundle exec unicorn -p 5000 -c /myapp/config/unicorn/production.rb -E production 
    volumes:
      - .:/myapp
    ports:
      - "5000:5000"
    depends_on:
      - db
  nginx:
    build:
      context: .
      dockerfile: dockerfiles/nginx/Dockerfile
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web
