FROM ruby:2.4.0

ENV APP_HOME /myapp
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

RUN apt-get update -qq && apt-get install -y git build-essential libpq-dev nodejs
RUN gem install bundler
RUN bundle config build.nokogiri --use-system-libraries

# setup Rails
ADD Gemfile
ADD Gemfile.lock

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
    BUNDLE_JOBS=4
RUN bundle install

ADD $APP_HOME
