default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password
  # Docker用に設定
  host: db

development:
  <<: *default
  database: todo_development
test:
  <<: *default
  database: todo_test
production:
  <<: *default
  database: todo_production
