default: &default
  adapter: postgresql
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password:
  host: db

development:
  <<: *default
  database: todo_development
test:
  <<: *default
  database: todo_test
production:
  <<: *default
  database: todo_production
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
