default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: todo_development
test:
  <<: *default
  database: todo_test
production:
  <<: *default
  database: todo_production
  username: todo
  password: <%= ENV['TODO_DATABASE_PASSWORD'] %>
